"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import { BASE_URL } from "@/lib/api";

export default function AIPage() {
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios.get(`${BASE_URL}/ai-insights`)
      .then(res => {
        setText(res.data.analysis);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-[#050505] text-white selection:bg-purple-500/30">
      <main className="max-w-4xl mx-auto px-6 py-24 space-y-12">
        
        {/* Header with AI Sparkle Aesthetic */}
        <header className="space-y-4">
          <div className="flex items-center gap-3">
            <div className="h-5 w-5 rounded-full bg-gradient-to-tr from-purple-500 to-blue-500 animate-pulse" />
            <span className="text-[10px] font-bold tracking-[0.3em] text-gray-500 uppercase">
              Neural Synthesis
            </span>
          </div>
          <h1 className="text-5xl font-semibold tracking-tight bg-gradient-to-b from-white to-white/50 bg-clip-text text-transparent">
            AI Insights
          </h1>
        </header>

        {loading ? (
          /* Apple-style Skeleton Loader */
          <div className="space-y-6 animate-pulse">
            <div className="h-4 w-3/4 bg-white/5 rounded-full" />
            <div className="h-4 w-full bg-white/5 rounded-full" />
            <div className="h-4 w-5/6 bg-white/5 rounded-full" />
            <div className="h-4 w-2/3 bg-white/5 rounded-full" />
          </div>
        ) : (
          /* Insight Container with Subtle Gradient Border */
          <div className="relative group">
            {/* The "Glow" behind the card */}
            <div className="absolute -inset-0.5 bg-gradient-to-r from-purple-500/20 to-blue-500/20 rounded-[2.5rem] blur opacity-50 group-hover:opacity-100 transition duration-1000" />
            
            <div className="relative bg-[#0a0a0a] border border-white/[0.08] rounded-[2.5rem] p-10 md:p-16">
              <div className="prose prose-invert max-w-none">
                <p className="text-xl md:text-2xl text-gray-200 leading-relaxed font-light whitespace-pre-wrap tracking-wide italic">
                  {text || "No insights available for the current projection."}
                </p>
              </div>
              
              <div className="mt-12 pt-8 border-t border-white/[0.05] flex items-center justify-between">
                <span className="text-[10px] font-medium text-gray-600 uppercase tracking-widest">
                  Generated by Latent-Explorer-v1
                </span>
                <button 
                  onClick={() => window.print()}
                  className="text-[10px] font-bold text-blue-500 uppercase tracking-widest hover:text-blue-400 transition-colors"
                >
                  Export Report
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Footer Detail */}
        <footer className="pt-20 text-center">
          <p className="text-xs text-gray-700 font-medium tracking-tighter">
            Insights are based on current UMAP clustering and cross-modal entropy scores.
          </p>
        </footer>
      </main>
    </div>
  );
}
